## 10. 예외처리

### 에러와 예외

<br>

**에러**

응용프로그램 실행 오류가 발생하는 것을 에러라고 한다.  
JVM 실행에 문제가 생겼다는 것으로, 실행 불능이 되며 개발자는 이런 에러에 대처할 방법이 없다.

<br>

**예외**

사용자의 잘못된 조작 또는 개발자의 잘못된 코딩으로 인해 발생하는 프로그램 오류를 말한다.  
예외가 발생하면 프로그램이 곧바로 종료된다는 점에서 에러와 동일하지만, 예외는 `예외 처리`를 통해 프로그램을 종료하지 않고 정상 실행 상태가 되도록 유지할 수 있다.

<br>

#### 예외의 종류
컴파일 시, 예외 처리를 확인하는 차이일 뿐, 두 가지 예외는 모두 예외 처리가 필요하다.

<br>

**일반 예외 (Exception)**

컴파일러 체크 예외라고도 부르며, 자바 소스를 컴파일하는 과정에서 예외 처리 코드가 필요한지 검사한다.  
Exception을 상속받지만 RuntimeException을 상속받지 않는 클래스들이 해당한다.

<br>

**실행 예외 (Runtime Exception)**

컴파일하는 과정에서 예외 처리 코드를 검사하지 않는다.  
RuntimeException을 상속받는 클래스들이 해당한다.  
자바 컴파일러가 체크를 하지 않기 때문에 개발자 경험에 의해 예외 처리 코드를 삽입해야 한다.  
예외 처리 코드를 넣지 않고 해당 예외가 발생하면 프로그램이 종료된다.

<br>

<u>실행 예외의 종류</u>

NullPointerException

객체가 없는 상태에서 객체를 사용하려 했을 때 발생
``` java
String data = null;
System.out.println(data.toString());    // NullPointerException 발생
```

<br>

ArrayIndexOutOfBoundsException

배열에서 인덱스 범위를 초과하여 사용할 경우에 발생

<br>

NumberFormatException

숫자로 변환될 수 없는 문자가 포함되어 있으면 발생

``` java
String data1 = "100";
String data2 = "a100";

int value1 = Integer.parseInt(data1);
int value2 = Integer.parseInt(data2);   // NumberFormatException 발생

int result = value1 + value2;

System.out.println(data1 + ", " + data2 + ", " + result);
```

<br>

ClassCastException

변환될 수 없는 클래스인데도, 억지로 타입 변환을 시도할 경우 발생

Dog, Cat 클래스가 Animal 클래스를 상속하고 있는 경우
``` java
Animal animal = new Dog();
Cat cat = (cat) animal; // ClassCastException 발생
```

<br>

### 예외처리
프로그램에서 예외가 발생했을 경우에 대비하기 위해 작성하는 코드이다.

<br>

#### 예외처리 목적
1. 예외 발생으로 인한 실행 중인 프로그램의 비정상 종료를 막기 위해서
2. 개발자에게 알리고 코드를 보완할 수 있도록 하기 위해서

모든 예외 클래스는 Trowable의 자손 클래스이며 크게 두 종류로 나뉜다.
- Error
    - 프로그램이 종료되어야 하는 심각한 문제를 표현한 것  
    대부분 컴퓨터나 JVM이 시스템적으로 동작할 수 없는 상황을 의미한다.

- Exception
    - 프로그램이 종료되지는 않지만 예외나 문제상황을 표현하기 위해 사용

<br>

### try-catch(-finally) 형식
``` java
int number = 10;
int result;

for (int i=10; i>=0; i--) {
    try {
        result = number / i;
        System.out.println(result);
    } catch (Exception e) {
        System.out.println("Exception 발생"+e.getMessage());
    } finally {
        System.out.println("항상 실행하는 finally");
    }
}
```
try부분에서 예외가 발생하면 catch블럭으로 이동한다.  
finally부분은 예외처리 유무에 관계없이 실행된다.

<br>

### 다중 catch
다양한 종류의 예외가 발생할 경우를 대비하기 위해 다중 catch를 사용해 예외별로 예외 처리 코드를 작성할 수 있다.

``` java
try {
    ...
} catch (ArrayIndexOutOfBoundsException e) {
    // 예외처리
} catch (Exception e) {
    // 예외처리
}
```
주의할 점은 상위 예외 클래스가 하위 예외 클래스보다 아래쪽에 위치해야 한다.

<br>

### 멀티 catch
하나의 catch 블록에서 여러 개의 예외를 처리할 수 있도록 하는 기능이다.

``` java
try {
    ...
} catch (ArrayIndexOutOfBoundsException e | NumberFormatException e) {
    // 예외 처리
} catch (Excepiton e) {
    // 예외 처리
}
```

<br>

### try-with-resource 형식

입출력과 함께 자주 쓰이는 구문으로, 일반적으로 사용한 자원을 닫아주는데 편리하다는 장점이 있다.
``` java
try (FileOutputStream out = new FileOutputStream("test.txt")) {
    out.write("Hello Sparta".getBytes());
    out.flush();
} catch (IOException e) {
    System.out.println("IOException 발생: "+e.getMessage());
    e.printStackTrace();
}
```
따로 close()를 호출하지 않아도, try문을 벗어나는 순간 자동적으로 close()가 호출되어 편리하다.

주의할 점은, 자원 객체는 java.lang.AutoCloseable 인터페이스를 구현하고 있어야 한다.  
AutoCloseable에는 close() 메소드가 정의되어 있는데, try-with-resource문이 close() 메소드를 자동 호출한다.

<br>

### 메소드에 예외 선언하기
'throws'키워드를 사용해 메소드에 예외를 선언할 수 있다.
예외처리를 해당 메소드에서 하지 않고 호출하는 쪽에서 처리하도록 미루는 것 (예외를 던진다, 떠넘긴다라고도 표현)

``` java
void method() throws IndexOutOfBoundsException, IllegalArgumentException {
    // 메소드의 내용
}
```
method()를 호출하는 쪽에서 아래와 같은 작업을 해야한다.
1. 예외를 처리한다. (try-catch)
2. 예외를 선언해 호출하는 쪽에서 처리하게끔 한다. (throws)

<br>

### 사용자 정의 예외
개발자가 직접 정의해서 만든 예외를 의미한다.

<br>

#### 사용자 정의 예외 클래스 선언
일반 예외로 선언할 경우 Exception을 상속하면 되고,  
실행 예외로 선언할 경우에는 RuntimeException을 상속하면 된다.

``` java
public class XXXException extends [ Exception | RuntimeException ] {
    public XXXException() { }
    public XXXException(String message) { super(message); }
}
```
생성자를 포함하고, 매개변수를 갖는 생성자는 상위 클래스의 생성자를 호출해서 예외 메세지를 넘겨준다.

<br>

### 예외 발생시키기
코드에서 예외를 발생시키는 것이다.

``` java
throw new XXXException();
throw new XXXException("메세지");
```

### 예시

``` java
// 사용자 정의 예외
public class BalanceInsufficientException extends Exception {
    public BalanceInsufficientException() {}
    public BalanceInsufficientException(String msg) { super(msg); }
}
```
사용자 정의 예외를 선언했다.  
Exception 예외를 상속받았기 때문에 일반 예외이며, 예외 처리를 해주지 않으면 컴파일 오류가 발생한다.

<br>

``` java
public class Account {
    private long balance;

    public Account() {}

    public long getBalance() {
        return balance;
    }

    public void deposit(int money) {
        balance += money;
    }

    // 사용자 정의 예외 떠넘기기
    public void withdraw(int money) throws BalanceInsufficientException{
        if (balance < money) {
            // 예외 발생
            throw new BalanceInsufficientException("잔고부족: " + (money-balance) + " 모자람");
        }
        balance -= money;
    }
}
```
withdraw() 메소드에 예외를 발생시키도록 구현되었고, 호출하는 쪽으로 예외 처리를 떠넘겼다.

<br>

``` java
Account account = new Account();

account.deposit(10000);
System.out.println("예금액: " + account.getBalance());

// 예외처리
try {
    account.withdraw(30000);
} catch (BalanceInsufficientException e) {
    System.out.println(e.getMessage());
    e.printStackTrace();
}
```
main()에서 withdraw()를 호출하기 때문에 예외 처리를 해주었다.